feat(show-progress): add show progress support
react-component/notification pull request #322
Opened 2024-04-09 07:58 UTC by yociduo

https://github.com/ant-design/ant-design/issues/48125

2024-05-06 06:53 UTC, afc163 commented on README.md
> +| IE11, Edge
别动这个。

2024-05-06 06:53 UTC, afc163 commented on README.md
> +          <td></td>
```suggestion
          <td>false</td>
```

2024-05-06 06:54 UTC, afc163 commented on src/Notice.tsx
> +import { Line } from 'rc-progress';
自行实现进度条样式吧，不依赖 rc-progress。

2024-05-06 09:20 UTC, yociduo commented on README.md
> +| IE11, Edge
prettier干的

2024-05-06 09:39 UTC, afc163 commented on src/Notice.tsx
> +        </div>
用 https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress 这个如何

2024-05-07 02:54 UTC, yociduo commented on src/Notice.tsx
> +        </div>
更新了

2024-05-07 03:06 UTC, afc163 commented on src/Notice.tsx
> +        </div>
兼容性很好的。

2024-05-07 03:19 UTC, afc163 commented on src/Notice.tsx
> +        <div className={`${noticePrefixCls}-progress-wrapper`}>
这个 wrapper 还需要么

2024-05-07 03:22 UTC, yociduo commented on src/Notice.tsx
> +        <div className={`${noticePrefixCls}-progress-wrapper`}>
可以去掉的

2024-05-07 03:36 UTC, afc163 commented on docs/examples/hooks.tsx
> +            Show With Progress
单独搞一个 demo 吧，别改这个 hooks 的。

2024-05-07 03:43 UTC, yociduo commented on docs/examples/hooks.tsx
> +            Show With Progress
好的，我看这个是重复的就改掉了，下午加一下

2024-05-07 10:53 UTC, afc163 commented
1. hover 到 notificiation 上时，progress 应该是暂停，不应该消失。
2. 是否应该是反向 progresss？

参考 https://fkhadra.github.io/react-toastify/introduction/

2024-05-08 01:24 UTC, yociduo commented
> 1. hover 到 notificiation 上时，progress 应该是暂停，总之不应该消失。看上去还需要一个 `pauseOnHover: boolean;`。
> 2. 是否应该是反向 progresss？
> 
> 参考 https://fkhadra.github.io/react-toastify/introduction/

1. 是沿用旧逻辑，这是新开个pr改，还是就在当前这个改掉。我觉得加了这个的话，`closeOnClick: boolean`也应该加上
2. 这个倒是正反的都看到过，按你说的我改一下，改成反向的

2024-05-08 02:25 UTC, afc163 commented
showProgress 就行了。

2024-05-11 01:55 UTC, afc163 commented
hover 后现在是暂停的，但是鼠标离开后重新计时了，预期应该是从上次时刻继续。

2024-05-11 01:56 UTC, afc163 requested changes
hover 后现在是暂停的，但是鼠标离开后重新计时了，预期应该是从上次时刻继续。

2024-05-11 03:32 UTC, yociduo commented
> hover 后现在是暂停的，但是鼠标离开后重新计时了，预期应该是从上次时刻继续。

这个更新了，顺便加了一下测试用例

2024-05-11 04:26 UTC, merged